date: 2026-01-08
topic: Diffusion forcing, Self forcing
speaker: 张欣宇
papers: 
  - title: Diffusion forcing
    url: https://arxiv.org/abs/2407.01392
  - title: Self forcing
    url: https://arxiv.org/abs/2506.08009